### ISSUE TITLE
Some error using back translation in the uda!

### ISSUE THREAD

**Issue by iimlearning** [google-research/uda#104]
I run the following code in the colab:

!git clone https://github.com/google-research/uda.git

cd uda/back_translate/

pip install --user nltk
python -c "import nltk; nltk.download('punkt')"
pip install --user tensor2tensor==1.13.4

!bash download.sh

!bash run.sh

All ran successfully without !bash run.sh
the error:

![image](https://user-images.githubusercontent.com/46561673/110088794-44732b00-7dd0-11eb-9fc2-6ecd89b20d9e.png)

The question maybe is version compatibility in the TensorFlow, nltk, and tensor2tensor.

but, what is the right version if I use colab to run the uda back translation code?

Somebody can give me the answer? thank you very much!!

**Comment by Lucecpkn** [comment]
I have run into the same issue. It's probably because you have installed newer TensorFlow >= 2 while this project relies on the old TensorFlow 1.

You might have to try degrading your TF to v 1.xx.  
Not sure if the authors are gonna upgrade the project to be compatible to more 'modern' versions of libraries.

**Comment by iimlearning** [comment]
> I have run into the same issue. It's probably because you have installed newer TensorFlow >= 2 while this project relies on the old TensorFlow 1.
> 
> You might have to try degrading your TF to v 1.xx.
> Not sure if the authors are gonna upgrade the project to be compatible to more 'modern' versions of libraries.

Thanks for your reply.
I tried the tensorflow1.5 in the colab some days ago, but there were also some errors indicate that the project need tensorflow > 2.1.
So, I have used another project to use UDA, I will close this comment right now.

Thanks.
