### ISSUE TITLE
IMDb task hyperparameters about 'uda_softmax_temp' and 'uda_confidence_thresh'

### ISSUE THREAD

**Issue by SanghunYun** [google-research/uda#23]
Hi, I'm trying to re-implement UDA for IMDb task.

I have some curiosity about hyperparameters. 
(About this results)
![image](https://user-images.githubusercontent.com/45596437/62356278-acee8c00-b54b-11e9-9d0b-c3603dcc3d3e.png)

When I saw the script 'run_base_uda.sh' there is no 'uda_softmax_temp' and 'uda_confidence_thresh'.
Also, 'uda_softmax_temp' and 'uda_confidence_thresh' are -1(default) at main.py

Is IMDb task does not use sharpening prediction and only use TSA method??

**Comment by qizhex** [comment]
Hi, sharpening does not help a lot on IMDb, but for the [SOTA performance](https://github.com/google-research/uda/blob/master/text/scripts/train_large_ft_uda_tpu.sh#L41), we set uda_softmax_temp to 0.85.

**Comment by SanghunYun** [comment]
Thank you!
I'll try that hyperparameters.
