### ISSUE TITLE
download_cifar10.sh

### ISSUE THREAD

**Issue by sweetTT** [google-research/uda#3]
Hello!
In download_cifar10.sh,what's the meaning of variable j, the correspoding code is following:

aug_copy_end=$( expr $aug_copy - 1)
for i in `seq 0 $aug_copy_end`;
do
  for j in `seq 0 12`;
  do
    wget $url_prefix/unsup-$i.tfrecord.$j
  done
done

**Comment by qizhex** [comment]
Different unsup-$i.tfrecord.$j is the j-th part of the unsupervised set. They are saved into several files since each tfrecord file has a maximum number of examples.
