### ISSUE TITLE
Possible Overlap in CIFAR Data

### ISSUE THREAD

**Issue by wilbry** [google-research/uda#30]
Looking at `main` in https://github.com/google-research/uda/blob/master/image/preprocess.py, it seems that the supervised and unsupervised sets are being drawn from the same data independently, so there is likely to be overlap of images in the supervised and unsupervised sets. Do you think this affects your data in any way? Or am I misreading the code?

**Comment by qizhex** [comment]
Yes, we followed ICT and included labeled training data in the unlabeled set. The code for the data split of ICT is available [here](https://github.com/vikasverma1077/ICT/blob/master/utils.py#L224).

We also tried to exclude the labeled training data from the unlabeled set. The accuracy on CIFAR-10 with 4,000 examples is 94.66+-0.17, similar to the original performance 94.73+-0.11.

**Comment by wilbry** [comment]
Thanks for the explanation!
