### ISSUE TITLE
why only use uda_softmax_temp for ori_log_probs but not for aug_log_probs?

### ISSUE THREAD

**Issue by rankeey** [google-research/uda#35]
https://github.com/google-research/uda/blob/e4f225e496064b983be8c8592ba9220c8d8cd1cb/text/uda.py#L159
why only use uda_softmax_temp for ori_log_probs but not for aug_log_probs?

**Comment by qizhex** [comment]
When the entropy of the original unlabeled examples is reduced, the entropy of the augmented unlabeled examples will be reduced as well due to the consistency loss.

**Comment by rankeey** [comment]
thanks for your sharing
