### ISSUE TITLE
NotFoundError: IMDB_raw/csv/train.csv not found

### ISSUE THREAD

**Issue by Tilana** [google-research/uda#4]
Hello,

after downloading the IMDB data and the BERT model an error pops up when running the preprocessing script:
_NotFoundError: data/IMDB_raw/csv/train.csv; No such file or directory._

It seems the structure of the data downloaded via the bash script is different than the file path specified in _/scripts/prepro.sh_. I do have a IMDB_raw folder containing a _train_id_list.txt file_, as well as an _aclImdb_ folder, however no _train.csv_ file.

Did I miss a step for processing the data to the correct format or is there an issue when downloading the data? 

Any help is appreciated.

**Comment by qizhex** [comment]
Have you run "bash scripts/download.sh"?

**Comment by Tilana** [comment]
Sure. This is how my folder structure looks after running: _bash scripts/download.sh_:
![Selection_024](https://user-images.githubusercontent.com/10959995/60239211-26d88900-98ad-11e9-9c85-6bac168a1ec2.png)
The preprocessing script which is the next step in the README instructions, however, requires a _data/IMDB_raw/csv/train.csv_ file which is not created during the download.

**Comment by qizhex** [comment]
In the download script, there is a command used to generate the csv files: "python utils/imdb_format.py --raw_data_dir=data/IMDB_raw/aclImdb --train_id_path=data/IMDB_raw/train_id_list.txt --output_dir=data/IMDB_raw/csv". 

Maybe this command didn't run successfully?

**Comment by Tilana** [comment]
Yes, thanks! That was exactly the issue.
Running the command the generated the missing file.
