### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: data/proc_data/IMDB/train_20; No such file or directory

### ISSUE THREAD

**Issue by imayachita** [google-research/uda#46]
Hi all,
I got this problem when running prepro.sh. Anyone got the same problem? Is it possible that because I am using python 3? Thanks!

**Comment by luckysunda** [comment]
I have also got the same error!

**Comment by luckysunda** [comment]
> Hi all,
> I got this problem when running prepro.sh. Anyone got the same problem? Is it possible that because I am using python 3? Thanks!

Hey, have you solved this issue as I see you have closed this issue!
