### ISSUE TITLE
Code for Implementing RandAugment

### ISSUE THREAD

**Issue by varunnair18** [google-research/uda#49]
Hello, 

Congratulations on being accepted as an ICLR 2020 Paper! I noticed in the conference version of the paper, you use RandAugment instead of AutoAugment to generate copies of the unlabeled data.

Will you be uploading the code necessary to duplicate that technique in this repo soon? That would be very useful for the research community as it is much more computationally efficient than running AutoAugment and achieves comparable results.

Thanks!

**Comment by qizhex** [comment]
Hi, the paper is actually under review at ICLR 2020. We'll upload the code and dumped data for RandAugment in a couple of days.

**Comment by varunnair18** [comment]
I see, your paper is uploaded to arxiv currently as being accepted to ICLR 2020, it might be worth fixing this typo. @qizhex 
![image](https://user-images.githubusercontent.com/15525087/65908690-f06f4600-e394-11e9-984c-797b150f2097.png)

Looking forward to using your code for RandAugment soon!

**Comment by qizhex** [comment]
Yea, thanks for letting me know! I have already updated it. The code for randaugment is uploaded. Feel free to try it out!

**Comment by varunnair18** [comment]
@qizhex Can you explain some of the choices that went into designing the RandAugment policy?

For example, in image/randaugment/policies.py, I see that you constructed the list of operations from which you randomly pick like this:

![image](https://user-images.githubusercontent.com/15525087/66213861-93260e00-e68e-11e9-8b48-bea49c28d185.png)

Why is it that the list of policies only contain parameter values starting at 0.5? 
`op_list += [(trans, 0.5, magnitude)]`
In the optimal policies for ImageNet, CIFAR10, and SVHN found by AutoAugment, they often start below 0.5. 

Also, why did you choose to apply pairs of random policies vs. only applying one policy or 3+ policies?
`policies += [[op_1, op_2]]`

**Comment by qizhex** [comment]
It just worked well in our first try so we didn't further tune the hyperparameters.

**Comment by varunnair18** [comment]
I see, thanks for uploading the code!
