### ISSUE TITLE
Relations between training batches number and training steps number?

### ISSUE THREAD

**Issue by vikotse** [google-research/uda#55]
In official IMDB text classification task, use 20 labeled training data, and batch_size=8, total 3 batches, and 10000 training steps.
It's almost training for 3333 epochs.

If I have 10000 labeled training data, it's unpractical to train for 3333 epochs.
If there exists a recommended way to choose the number of training steps for different amounts of training data?

**Comment by qizhex** [comment]
The training steps depends on the number of unlabeled examples you have and whether you use BERT to initialize. If you have 10k training examples and use BERT, maybe it works well to just train for 3 epochs. But I am not sure about that, so you need to try it yourself.

**Comment by vikotse** [comment]
> The training steps depends on the number of unlabeled examples you have and whether you use BERT to initialize. If you have 10k training examples and use BERT, maybe it works well to just train for 3 epochs. But I am not sure about that, so you need to try it yourself.

Thanks a lot.
