### ISSUE TITLE
Is the data convenient to disclose?

### ISSUE THREAD

**Issue by XiaoqingNLP** [google-research/uda#61]
![image](https://user-images.githubusercontent.com/12473617/67470727-d3225480-f680-11e9-9cb5-45bf79aba79c.png)
The IMDB data is disclosed, and the rest of the data is convenient to disclose? Although the article has added the corresponding reference, the corresponding data set is not disclosed in the corresponding article, so that it is difficult for the reader to find the corresponding data.
In addition, I am surprised that many of the data sources in the article only refer to the predecessors' articles, but the predecessor articles also do not disclose the data set and specify the processing method.

**Comment by qizhex** [comment]
It's available in the Appendix (page 17). We moved lots of contents to Appendix due to space limits.
