### ISSUE TITLE
Enforcing consistency on the unlabeled data

### ISSUE THREAD

**Issue by Albineti** [google-research/uda#64]
This is not really an issue but a question I have on the model itself. I don't know where I should post this or who to refer it to, so I post here. I am sorry for any inconvenience. 

I was quite surprised that you only consider enforcing consistency on the augmented data, and not between pairs of unlabeled data where the model is confident they belong to the same category, although what the category might be is not learned yet. This comes from the hypothesis that the model will first learn to infer that two texts talk about the same before understanding what they are talking about (like us humans do when, for instance, reading something written on a language we don't understand. We see the same words and can infer that they share something in common). 

I understand that this is precisely what the language model does; it maps similar texts close to each other on the high dimensional space. I just find surprising that you do not consider it further. I can imagine a situation where the unlabeled, high dimensional points are sufficiently sparsely distributed but the data augmentation doesn't give enough variability, in the sense that it only considers a small neighborhood around a point, so that in the end you have many regions of similar points in space, each around the unlabeled data, but these regions do not overlap. The information from the labeled examples won't flow as much as it could if they overlapped. This is precisely what I imagine you would accomplish by enforcing consistency on different pairs of unlabeled points. 

Thank you for your time!

**Comment by qizhex** [comment]
That's a nice idea! The model indeed has more power and gives more variability. If the trained model already learns reliable semantics, then it might be a good idea to use the model to measure if a pair of unlabeled data belong to the same category. However, if the model doesn't have enough data to learn, then it might be overfitting its own understanding of words and sentences.
