### ISSUE TITLE
Back-translation model source

### ISSUE THREAD

**Issue by voluntadpear** [google-research/uda#7]
I noticed that the `run.sh` script for Back-translation passes some Checkpoints to  `t2t` (e.g.: `checkpoints/enfr/model.ckpt-500000`). If I want to use another `t2t` problem for doing the back-translation instead of `translate_enfr_wmt32k` I would need to provide other checkpoints, right? How are these checkpoints generated? Is there any source code available for the original Machine Translation model used?

Also, is it possible to not use `tensor2tensor` and use another model to generate the paraphrases? I think that as long as I keep the output files structure it shouldn't be an issue. The reason I'm asking is that I want to try UDA with an Spanish dataset using a `ES-EN` back-translation augmentation techinque. But unfortunately `tensor2tensor` doesn't include it.

Thanks.

**Comment by qizhex** [comment]
The checkpoint is obtained by training on the translate_enfr_wmt32k problem using recommended hyperparameters of tensor2tensor. It is definitely possible to not use tensor2tensor but we did not try other machine translation systems so you might need to investigate it yourself. Thanks!

**Comment by voluntadpear** [comment]
Thank you!
