### ISSUE TITLE
Are crop and flip used on both labeled and unlabeled images?

### ISSUE THREAD

**Issue by jiequanz** [google-research/uda#71]
Are crop and flip used on both labeled and unlabeled images? After reading the code, I think they are used for all images, but want to make sure.

**Comment by qizhex** [comment]
Yes. We mentioned this in our updated paper "In the vision domain, simple augmentations including cropping and flipping are applied to labeled examples. To minimize the discrepancy between supervised training and prediction on unlabeled examples, we apply the same simple augmentations to unlabeled examples."
