### ISSUE TITLE
Compare with XLNet too

### ISSUE THREAD

**Issue by impredicative** [google-research/uda#9]
BERT is now far from the leading model e.g. on the [GLUE Benchmark](https://gluebenchmark.com/leaderboard/). Why not test with XLNet-Large for more a relevant comparison? Outside of Google, all else being equal, people would prefer to use the better model.

**Comment by qizhex** [comment]
Yes. XLNet has better performance. And both BERT and XLNet are done by Google :). We use BERT since UDA is done in parallel to XLNet. We currently do not have plans to adapt the codebase to XLNet but we would be happy to add links to repos that use XLNet.
